#!/bin/bash

if [ -e ~/.io_bench_params ]; then
        . ~/.io_bench_params
fi

if [ "$(echo ${args} | grep '\-qs')" = "" ]; then
	args="${args} -qs 32"
fi

if [ "$(echo ${args} | grep /dev/)" = "" ]; then
	echo ${HOME}/run_iobench/iobench ${args} /dev/dm*
	${HOME}/run_iobench/iobench ${args} /dev/dm*
else
	echo ${HOME}/run_iobench/iobench ${args}
	${HOME}/run_iobench/iobench ${args}
fi
echo EXITED
