#!/bin/bash

if [ "$(hostname)" != iota ]; then
	while [ 1 ]
	do
		while [ ! -e "${HOME}/.vrun_lock" ]
		do
			sleep 0.1
		done
		"${HOME}/script"
		rm -f "${HOME}/.vrun_lock"
	done
	exit 1
fi
rm -f "${HOME}/script"
ssh sigma rm -f "${HOME}/script"
ssh zeta rm -f "${HOME}/script"
echo $@ > "${HOME}/script"
chmod +x "${HOME}/script"
scp -p "${HOME}/script" zeta:
scp -p "${HOME}/script" sigma:
ssh sigma touch "${HOME}/.vrun_lock"
ssh zeta touch "${HOME}/.vrun_lock"
"${HOME}/script"

