#!/bin/bash

if [ "$(hostname)" != iota ]; then
	while [ 1 ]
	do
		while [ ! -e "${HOME}/.vrun_lock" ]
		do
			sleep 0.1
		done
		"${HOME}/run_iobench/script"
		rm -f "${HOME}/.vrun_lock"
	done
	exit 1
fi
rm -f "${HOME}/run_iobench/script"
ssh sigma rm -f "${HOME}/run_iobench/script"
ssh zeta rm -f "${HOME}/run_iobench/script"
echo $@ > "${HOME}/run_iobench/script"
chmod +x "${HOME}/run_iobench/script"
scp -p "${HOME}/run_iobench/script" "${HOME}/run_iobench/iobench" zeta:"${HOME}/run_iobench"
scp -p "${HOME}/run_iobench/script" "${HOME}/run_iobench/iobench" sigma:/"${HOME}/run_iobench"
ssh sigma touch "${HOME}/.vrun_lock"
ssh zeta touch "${HOME}/.vrun_lock"
"${HOME}/run_iobench/script"

